Create table all_player_ids(

Player text,

ID int)

Insert into all_player_ids
VALUES
("KiNgg",1),
("Yay",2),
("Derke",3),
("ZmjjKK",4),
("Will",5),
("Laz",6),
("Alfajer",7),
("Keznit",8),
("Jinggg",9),
("Ardiis",10),
("BuZz",11),
("Cryocells",12),
("Zyppan",13),
("Dgzin",14),
("Mazino",15),
("Dep",16),
("ScreaM",17),
("Smoggy",18),
("Less",19),
("Zekken",20),
("Jamppi",21),
("F0rsakeN",22),
("Aspas",23),
("NagZ",24),
("PANcada",25),
("SUYGETSU",26),
("MaKo",27),
("Victor",28),
("Crws",29),
("BcJ",30),
("Tehbotol",31),
("Saadhak",32),
("Foxz",33),
("Mistic",34),
("Crashies",35),
("Tacolilla",36),
("Shao",37),
("Sacy",38),
("D4v41",39),
("Qck",40),
("Rb",41),
("Bang",42),
("TENNN",43),
("Adverso",44),
("SugarZ3ro",45),
("SScary",46),
("Melser",47),
("Marved",48),
("Fl1pzjder",49),
("Nozwerr",50),
("Asuna",51),
("Boaster",52),
("Nivera",53),
("Shyy",54),
("BlaZek1ng",55),
("Surf",56),
("CHICHOO",57),
("Haodong",58),
("Delz1k",59),
("Zest",60),
("Dephh",61),
("Stax",62),
("Famouz",63),
("Life",64),
("AYRIN",65),
("Soulcas",66),
("Sushiboys",67),
("Derrek",68),
("Dimasick",69),
("Nobody",70),
("Benkai",71),
("FNS",72),
("Mindfreak",73),
("Stellar",74),
("Klaus",75),
("ANGE1",76),
("Enzo",77),
("Berserx",78),
("Khalil",79),
("Mazin",80),
("Crow",81),
("Whz",82),
("Demon1",83),
("AAAAY",84),
("Sayaplayer",85),
("Jawgemo",86),
("Fit1nho",87),
("Sayf",88),
("CNed",89),
("Cauanzin",90),
("Cloud",91),
("Munchkin",92),
("NAts",93),
("Something",94),
("MrFaliN",95),
("Lysoar",96),
("Yosemite",97),
("Yuicaw",98),
("Leo",99),
("Hoody",100),
("ATA KAPTAN",101),
("C0M",102),
("Ethan",103),
("QRaxs",104),
("Mojj",105),
("Qw1",106),
("Knight",107),
("Biank",108),
("Boostio",109),
("Xeta",110),
("Nukkye",111),
("Daveeys",112),
("Ban",113),
("Rhyme",114),
("S0m",115),
("Chronicle",116),
("Tuyz",117),
("Redgar",118),
("BerLIN",119),
("Carpe",120),
("Rin",121),
("TZH",122)

Update players_stats_2022 as p
set PlayerID = a.ID
from all_player_ids as a
where p.Player = a.Player

drop table players_stats_2022_1NF
Create table players_stats_2022_1NF(
Player text,
ID int,
Agent text)

insert into players_stats_2022_1NF
VALUES
("KiNgg",1,"Raze"),("KiNgg",1, "Viper"),("KiNgg",1, "KAY/O"),
("Yay",2,"Chamber"),("Yay",2, "Jett"),
("Derke",3,"Chamber"),("Derke",3, "Jett"),
("ZmjjKK",4,"Chamber"),("ZmjjKK",4, "Raze"),
("Will",5,"Raze"),("Will",5, "Chamber"),("Will",5, "Jett"),
("Laz",6,"Chamber"),("Laz",6, "KAY/O"),("Laz",6, "Skye"),
("Alfajer",7,"Raze"),("Alfajer",7, "Neon"),("Alfajer",7, "Killjoy"),
("Keznit",8,"KAY/O"),("Keznit",8, "Jett"),("Keznit",8, "Raze"),
("Jinggg",9,"Raze"),("Jinggg",9, "Reyna"),("Jinggg",9, "Sage"),
("Ardiis",10,"Chamber"),("Ardiis",10, "Jett"),("Ardiis",10, "KAY/O"),
("BuZz",11,"Jett"),("BuZz",11, "Chamber"),("BuZz",11, "Raze"),
("Cryocells",12,"Chamber"),("Cryocells",12, "Jett"),
("Zyppan",13,"Raze"),("Zyppan",13, "KAY/O"),("Zyppan",13, "Skye"),
("Dgzin",14,"Chamber"),("Dgzin",14, "Jett"),("Dgzin",14, "KAY/O"),
("Mazino",15,"Sage"),("Mazino",15, "KAY/O"),("Mazino",15, "Skye"),
("Dep",16,"Jett"),("Dep",16, "Neon"),("Dep",16, "Omen"),
("ScreaM",17,"Raze"),("ScreaM",17, "Phoenix"),
("Smoggy",18,"Jett"),("Smoggy",18, "KAY/O"),
("Less",19,"Viper"),("Less",19, "Chamber"),("Less",19, "Killjoy"),
("Zekken",20,"Neon"),("Zekken",20, "Raze"),("Zekken",20, "Sova"),
("Jamppi",21,"Chamber"),("Jamppi",21, "Sage"),
("F0rsakeN",22,"Chamber"),("F0rsakeN",22, "Jett"),("F0rsakeN",22, "Yoru"),
("Aspas",23,"Raze"),("Aspas",23, "Jett"),("Aspas",23, "Chamber"),
("NagZ",24,"Chamber"),("NagZ",24, "Killjoy"),("NagZ",24, "Sage"),
("PANcada",25,"Omen"),("PANcada",25, "Brimstone"),("PANcada",25, "Viper"),
("SUYGETSU",26,"Viper"),("SUYGETSU",26, "Sage"),("SUYGETSU",26, "Cypher"),
("MaKo",27,"Viper"),("MaKo",27, "Omen"),("MaKo",27, "Astra"),
("Victor",28,"KAY/O"),("Victor",28, "Raze"),("Victor",28, "Jett"),
("Crws",29,"Breach"),("Crws",29, "Omen"),("Crws",29, "Astra"),
("BcJ",30,"Fade"),("BcJ",30, "Omen"),("BcJ",30, "Sova"),
("Tehbotol",31,"Breach"),("Tehbotol",31, "Omen"),("Tehbotol",31, "Viper"),
("Saadhak",32,"KAY/O"),("Saadhak",32, "Skye"),("Saadhak",32, "Breach"),
("Foxz",33,"Yoru"),("Foxz",33, "Skye"),("Foxz",33, "Phoenix"),
("Mistic",34,"Skye"),("Mistic",34, "KAY/O"),("Mistic",34, "Breach"),
("Crashies",35,"Sova"),("Crashies",35, "Skye"),("Crashies",35, "Fade"),
("Tacolilla",36,"Chamber"),("Tacolilla",36, "Skye"),
("Shao",37,"Fade"),("Shao",37, "Sage"),("Shao",37, "Sova"),
("Sacy",38,"Fade"),("Sacy",38, "Sova"),
("D4v41",39,"Sage"),("D4v41",39, "Skye"),("D4v41",39, "Fade"),
("Qck",40,"Killjoy"),("Qck",40, "Chamber"),("Qck",40, "Sage"),
("Rb",41,"Killjoy"),("Rb",41, "KAY/O"),("Rb",41, "Chamber"),
("Bang",42,"Brimstone"),("Bang",42, "Omen"),("Bang",42, "Viper"),
("TENNN",43,"Raze"),("TENNN",43, "Killjoy"),("TENNN",43, "KAY/O"),
("Adverso",44,"Sova"),("Adverso",44, "Breach"),("Adverso",44, "Viper"),
("SugarZ3ro",45,"Brimstone"),("SugarZ3ro",45, "Astra"),("SugarZ3ro",45,"Omen"),
("SScary",46,"Viper"),("SScary",46, "Omen"),
("Melser",47,"Omen"),("Melser",47, "Astra"),("Melser",47, "Sage"),
("Marved",48,"Brimstone"),("Marved",48, "Omen"),("Marved",48, "Astra"),
("Fl1pzjder",49,"Viper"),("Fl1pzjder",49, "Chamber"),("Fl1pzjder",49, "KAY/O"),
("Nozwerr",50,"Sova"),("Nozwerr",50, "Fade"),
("Asuna",51,"KAY/O"),("Asuna",51, "Skye"),("Asuna",51, "Raze"),
("Boaster",52,"Brimstone"),("Boaster",52, "Omen"),("Boaster",52, "Viper"),
("Nivera",53,"Viper"),("Nivera",53, "KAY/O"),("Nivera",53, "Breach"),
("Shyy",54,"Fade"),("Shyy",54, "KAY/O"),
("BlaZek1ng",55,"Brimstone"),("BlaZek1ng",55, "Fade"),("BlaZek1ng",55, "Astra"),
("Surf",56,"Chamber"),("Surf",56, "Jett"),
("CHICHOO",57,"Viper"),("CHICHOO",57, "Omen"),("CHICHOO",57, "Astra"),
("Haodong",58,"Breach"),("Haodong",58, "Skye"),("Haodong",58, "Viper"),
("Delz1k",59,"Omen"),("Delz1k",59, "Viper"),("Delz1k",59, "Brimstone"),
("Zest",60,"Fade"),("Zest",60, "Sova"),
("Dephh",61,"KAY/O"),("Dephh",61, "Breach"),("Dephh",61, "Cypher"),
("Stax",62,"Breach"),("Stax",62, "Skye"),("Stax",62, "Fade"),
("Famouz",63,"Chamber"),("Famouz",63, "Raze"),("Famouz",63, "Sova"),
("Life",64,"Jett"),
("AYRIN",65,"Astra"),("AYRIN",65, "Sage"),("AYRIN",65, "Viper"),
("Soulcas",66,"Fade"),("Soulcas",66, "Skye"),("Soulcas",66, "KAY/O"),
("Sushiboys",67,"Killjoy"),("Sushiboys",67, "Neon"),("Sushiboys",67, "Breach"),
("Derrek",68,"Fade"),("Derrek",68, "Breach"),("Derrek",68, "Sova"),
("Dimasick",69,"Omen"),("Dimasick",69, "Brimstone"),("Dimasick",69, "Sova"),
("Nobody",70,"Fade"),("Nobody",70, "Sova"),
("Benkai",71,"Fade"),("Benkai",71, "Cypher"),("Benkai",71, "Sage"),
("FNS",72,"Viper"),("FNS",72, "Killjoy"),("FNS",72, "Breach"),
("Mindfreak",73,"Astra"),("Mindfreak",73, "Viper"),("Mindfreak",73, "Brimstone"),
("Stellar",74,"Viper"),("Stellar",74, "Sage"),("Stellar",74, "KAY/O"),
("Klaus",75,"Sova"),("Klaus",75, "Fade"),("Klaus",75, "Viper"),
("ANGE1",76,"Omen"),("ANGE1",76, "Fade"),("ANGE1",76, "Brimstone"),
("Enzo",77,"Fade"),("Enzo",77, "Viper"),("Enzo",77, "Sova"),
("Berserx",78,"Neon"),("Berserx",78, "Jett"),("Berserx",78, "Skye"),
("Khalil",79,"Omen"),("Khalil",79, "Viper"),
("Mazin",80,"KAY/O"),("Mazin",80, "Jett"),("Mazin",80, "Breach"),
("Crow",81,"Breach"),("Crow",81, "Fade"),("Crow",81, "Skye")

Update players_stats_2022_1NF
Set Agent = lower(Agent)

drop view players_stats_2022_1NF_view
Create view players_stats_2022_1NF_view as
select p.Player,p.PlayerID,p.Country,p.Team,p1nf.Agent,p.Maps,p.K,p.D,p.A,p.KD,p.KDA,p."ACS/Map",p."D/Map",p."A/Map"from players_stats_2022 as p
join players_stats_2022_1NF as p1nf
on PlayerID = ID
